"""1D steady-state thermal modeling.

Stage 1 of the thermal modeling roadmap:
  * steady_state_geotherm   — layered temperature profile
  * thermal_conductivity_with_porosity — geometric mean mixing
  * effective_conductivity_column     — depth-dependent k
  * maturity_easy_ro        — Sweeney & Burnham (1990) Easy%Ro kinetics

No GUI or Qt dependencies.
"""
from __future__ import annotations

import numpy as np


# ---------------------------------------------------------------------------
# Geotherm
# ---------------------------------------------------------------------------

def steady_state_geotherm(
    layers: list[dict],
    surface_temp_C: float = 10.0,
    basal_heat_flow_mW: float = 60.0,
) -> list[tuple[float, float]]:
    """Compute the steady-state temperature profile through a layered column.

    Uses the 1D steady-state heat equation for each layer::

        T(z) = T_top + (q / k) * dz - (A / 2k) * dz²

    where q is the heat flow at the *top* of the layer (W/m²), k is
    thermal conductivity (W/m·K), and A is volumetric heat production (W/m³).

    The surface heat flow is derived from the basal heat flow plus the total
    heat generated by all layers::

        q_surface = q_basal + Σ (A_i × dz_i)

    Going downward, q decreases by A·dz at each layer (heat produced above
    adds to the upward flux, so the downward flux below each layer is smaller).

    Parameters
    ----------
    layers:
        Top-to-bottom list of dicts, each with:

        =====================  =========================================
        Key                    Description
        =====================  =========================================
        z_top                  Top depth (m, positive down)
        z_bottom               Base depth (m)
        thermal_conductivity   k (W/m·K)
        heat_production        A (µW/m³); optional, defaults to 0
        =====================  =========================================

    surface_temp_C:
        Temperature at z = 0 (°C).
    basal_heat_flow_mW:
        Heat flow entering the base of the column (mW/m²).

    Returns
    -------
    list[tuple[float, float]]
        ``(depth_m, temperature_C)`` pairs at the surface, every ~100 m
        through each layer, and at each layer base.
    """
    q_basal = basal_heat_flow_mW * 1e-3   # mW/m² → W/m²

    # Surface heat flow = basal + all radiogenic heat produced in the column
    q_surface = q_basal + sum(
        layer.get("heat_production", 0.0) * 1e-6 * (layer["z_bottom"] - layer["z_top"])
        for layer in layers
    )

    results: list[tuple[float, float]] = [(0.0, surface_temp_C)]
    T_current = surface_temp_C
    q = q_surface        # heat flow at the top of the current layer

    for layer in layers:
        k = layer["thermal_conductivity"]
        if k <= 0:
            k = 2.0      # safety fallback
        A = layer.get("heat_production", 0.0) * 1e-6   # µW/m³ → W/m³
        dz = layer["z_bottom"] - layer["z_top"]

        # Intermediate points: ~one per 100 m (minimum 2)
        n_points = max(2, int(dz / 100))
        for i in range(1, n_points + 1):
            frac = i / n_points
            dz_i = dz * frac
            z = layer["z_top"] + dz_i
            T = T_current + (q / k) * dz_i - (A / (2.0 * k)) * dz_i ** 2
            results.append((z, T))

        # Advance state to bottom of this layer
        T_current = T_current + (q / k) * dz - (A / (2.0 * k)) * dz ** 2
        q -= A * dz      # heat flow decreases going down (heat produced above adds to upward flux)

    return results


# ---------------------------------------------------------------------------
# Thermal conductivity mixing
# ---------------------------------------------------------------------------

def thermal_conductivity_with_porosity(
    k_matrix: float,
    k_fluid: float,
    porosity: float,
) -> float:
    """Geometric mean mixing model for bulk thermal conductivity.

    k_bulk = k_matrix^(1 - phi) × k_fluid^phi

    Parameters
    ----------
    k_matrix:
        Grain / matrix thermal conductivity (W/m·K).
    k_fluid:
        Pore fluid thermal conductivity (W/m·K).
    porosity:
        Porosity [0, 1].

    Returns
    -------
    float
        Bulk thermal conductivity (W/m·K).
    """
    if porosity <= 0.0:
        return float(k_matrix)
    if porosity >= 1.0:
        return float(k_fluid)
    return float(k_matrix ** (1.0 - porosity) * k_fluid ** porosity)


def effective_conductivity_column(
    layers: list[dict],
    k_fluid: float = 0.6,
) -> list[dict]:
    """Porosity-weighted effective thermal conductivity for each layer.

    Applies Athy's law to compute porosity at the layer midpoint, then uses
    the geometric mean mixing model to obtain the bulk (effective) conductivity.

    Parameters
    ----------
    layers:
        List of layer dicts, each with:

        ====================  ====================================================
        Key                   Description
        ====================  ====================================================
        z_top                 Top depth (m)
        z_bottom              Base depth (m)
        thermal_conductivity  Matrix grain conductivity (W/m·K)
        porosity_surface      phi0 (Athy); optional, default 0.5
        compaction_coeff      c (Athy, 1/m); optional, default 0.0005
        ====================  ====================================================

    k_fluid:
        Pore-fluid thermal conductivity (W/m·K).  Default 0.6 (water).

    Returns
    -------
    list[dict]
        Input dicts augmented with ``porosity_at_midpoint`` and
        ``effective_conductivity`` (W/m·K).
    """
    result = []
    for layer in layers:
        phi0 = layer.get("porosity_surface", 0.5)
        c    = layer.get("compaction_coeff", 0.0005)
        k_mat = layer["thermal_conductivity"]

        z_mid = (layer["z_top"] + layer["z_bottom"]) / 2.0
        phi = phi0 * np.exp(-c * z_mid)
        k_eff = thermal_conductivity_with_porosity(k_mat, k_fluid, phi)

        result.append({
            **layer,
            "porosity_at_midpoint":  float(phi),
            "effective_conductivity": float(k_eff),
        })
    return result


# ---------------------------------------------------------------------------
# Maturity — Easy%Ro (Sweeney & Burnham 1990)
# ---------------------------------------------------------------------------

# Activation energies (kcal/mol) and initial fractions from Table 2
_EA_KCAL = np.array([34, 36, 38, 40, 42, 44, 46, 48, 50, 52,
                     54, 56, 58, 60, 62, 64, 66, 68, 70, 72], dtype=float)
_EA_J    = _EA_KCAL * 4184.0                     # convert to J/mol
_F0      = np.array([0.03, 0.03, 0.04, 0.04, 0.05, 0.05, 0.06, 0.04, 0.04, 0.07,
                     0.06, 0.06, 0.06, 0.05, 0.05, 0.04, 0.03, 0.02, 0.02, 0.01])
_R       = 8.314    # gas constant (J/mol·K)
_A_FREQ  = 1e13     # frequency factor (1/s)


def maturity_easy_ro(
    thermal_history: np.ndarray,
    time_steps_ma: np.ndarray,
) -> float:
    """Compute vitrinite reflectance (%Ro) from a thermal history.

    Uses the Sweeney & Burnham (1990) Easy%Ro parallel first-order kinetic
    model with 20 reactions spanning Ea = 34–72 kcal/mol.

    Parameters
    ----------
    thermal_history:
        Temperature (°C) at each time step for the burial location.
        Must have the same length as ``time_steps_ma``.
    time_steps_ma:
        Geological time (Ma) corresponding to each temperature, in
        **decreasing** order (oldest first → 0 = present day).

    Returns
    -------
    float
        Vitrinite reflectance (%Ro).
    """
    thermal_history = np.asarray(thermal_history, dtype=float)
    time_steps_ma   = np.asarray(time_steps_ma,   dtype=float)

    f = _F0.copy()   # remaining fraction for each parallel reaction

    for i in range(len(time_steps_ma) - 1):
        dt_ma = abs(time_steps_ma[i] - time_steps_ma[i + 1])
        dt_s  = dt_ma * 1e6 * 365.25 * 24.0 * 3600.0   # Ma → seconds
        T_K   = thermal_history[i] + 273.15             # °C → K

        k_rate = _A_FREQ * np.exp(-_EA_J / (_R * T_K))
        f *= np.exp(-k_rate * dt_s)

    total_reacted = float(np.sum(_F0) - np.sum(f))
    return float(np.exp(-1.6 + 3.7 * total_reacted))
